### ISSUE TITLE
Issue with other addons

### ISSUE THREAD

**Issue by jbailey4** [MiguelMadero/ember-cli-bundle-loader#2]
I attempted to use this addon in my app which is also using Torii. Torii has an [instance-initializer](https://github.com/Vestorly/torii/blob/master/app%2Finstance-initializers%2Fsetup-routes.js#L14) that looks for the router, and when used with this addon the `applicationInstance.get('router')` is `undefined`. 

I'm not sure if this has to do with the customer "lazy-router" provided by this addon, this addon in general, or just a limitation using this addon with other certain addons. Still investigating.

**Comment by MiguelMadero** [comment]
Hi @jbailey4 apologies for missing your comment, I need to review my email filters, not sure why I never saw this. 

Did you find more details? 
I'm not familiar with Torii, but I could try this with a bit more info. I can't think of a reason why applicationInstance.get('router') would stop working, we're simply returning a different class. 

Also, it's important to keep in mind that we're making a lot more progress in the official solution for engines. We don't have an ETA, but for anything that's not super urgent, waiting might be a better bet (we're still using it, since we have an urgent need for this)

**Comment by MiguelMadero** [comment]
Hi @jbailey4 do you have any update on this?

**Comment by MiguelMadero** [comment]
@jbailey4 I'll leave this open in case someone else runs into it. Let me know if have more details about it and I can have a deeper look.

**Comment by MiguelMadero** [comment]
I'm closing this since there was no response for two years :)
